import { htmlToMarkdown } from "./html2md.js";
import { createZip } from "./zip.js";
import { extractPageSections, collectSidebarLinks } from "./extractor.js";
import { slugify, cleanTitle, summarize, estimateTokens, formatCount, frontmatter } from "./mdutil.js";

const els = {
  btn: document.getElementById("ingestBtn"),
  crawlBtn: document.getElementById("crawlBtn"),
  folderName: document.getElementById("folderName"),
  includeRaw: document.getElementById("includeRaw"),
  includeCombined: document.getElementById("includeCombined"),
  status: document.getElementById("status"),
  previewWrap: document.getElementById("previewWrap"),
  sectionList: document.getElementById("sectionList"),
  sectionCount: document.getElementById("sectionCount"),
};

function setStatus(msg, kind) {
  els.status.hidden = false;
  els.status.textContent = msg;
  els.status.className = "status" + (kind ? " " + kind : "");
}

async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}

async function run() {
  els.btn.disabled = true;
  setStatus("Reading page…");

  try {
    const tab = await getActiveTab();
    if (!tab || !tab.id) throw new Error("No active tab found.");
    if (/^(chrome|edge|about|chrome-extension):/.test(tab.url || "")) {
      throw new Error("Cannot ingest browser/internal pages. Open a real docs page.");
    }

    const [injection] = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: extractPageSections,
    });

    const result = injection && injection.result;
    if (!result || !result.ok) {
      throw new Error((result && result.error) || "Extraction failed.");
    }
    if (!result.sections.length) {
      throw new Error("No content sections detected on this page.");
    }

    setStatus(`Converting ${result.sections.length} sections to Markdown…`);

    const pageTitle = cleanTitle(result.title);
    const folder = slugify(els.folderName.value || pageTitle, "documentation");
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const usedNames = new Set();
    const files = [];
    const indexEntries = [];
    const combinedParts = [];
    let totalChars = 0;

    result.sections.forEach((section, i) => {
      const markdown = htmlToMarkdown(section.html);
      const num = String(i + 1).padStart(2, "0");
      let base = `${num}-${slugify(section.title, "section")}`;
      let name = `${base}.md`;
      let dedupe = 2;
      while (usedNames.has(name)) name = `${base}-${dedupe++}.md`;
      usedNames.add(name);

      const heading = "#".repeat(Math.max(1, section.level || 1));
      const sectionMd = `${heading} ${section.title}\n\n${markdown}`;
      const fm = frontmatter({
        title: cleanTitle(section.title),
        source: result.url,
        section_of: pageTitle,
        retrieved: dateStr,
        tokens_est: estimateTokens(sectionMd),
      });
      files.push({ name: `${folder}/${name}`, text: fm + sectionMd });
      combinedParts.push(sectionMd);
      totalChars += sectionMd.length;

      indexEntries.push({
        title: section.title,
        file: name,
        summary: summarize(markdown),
        tokens: estimateTokens(sectionMd),
      });

      if (els.includeRaw.checked) {
        files.push({ name: `${folder}/raw/${base}.html`, text: section.html });
      }
    });

    const totalTokens = estimateTokens(" ".repeat(totalChars));

    // Build index.md
    let index = frontmatter({ title: pageTitle, source: result.url, retrieved: dateStr, tokens_est: totalTokens });
    index += `# ${pageTitle}\n\n`;
    index += `> Ingested from [${result.url}](${result.url})\n`;
    index += `> on ${dateStr} · ${indexEntries.length} sections · ~${formatCount(totalTokens)} tokens\n\n`;
    index += `## Contents\n\n`;
    indexEntries.forEach((e, i) => {
      index += `${i + 1}. **[${e.title}](./${e.file})** — ${e.summary} _(~${formatCount(e.tokens)} tok)_\n`;
    });
    index += `\n---\n\n_Generated by 403 Whisperer — Docs to Markdown for AI (Chrome extension)._\n`;
    files.unshift({ name: `${folder}/index.md`, text: index });

    // Optional single combined file.
    if (els.includeCombined.checked) {
      const combined = frontmatter({ title: pageTitle, source: result.url, retrieved: dateStr, tokens_est: totalTokens }) +
        `# ${pageTitle}\n\n_Source: ${result.url}_\n\n` + combinedParts.join("\n\n");
      files.push({ name: `${folder}/combined.md`, text: combined });
    }

    setStatus("Building ZIP…");
    const blob = createZip(files, now);
    const url = URL.createObjectURL(blob);

    await chrome.downloads.download({
      url,
      filename: `${folder}.zip`,
      saveAs: false,
    });

    // Render preview.
    els.previewWrap.hidden = false;
    els.sectionCount.textContent = String(indexEntries.length);
    els.sectionList.innerHTML = "";
    indexEntries.forEach((e) => {
      const li = document.createElement("li");
      li.textContent = `${e.title} → ${e.file}`;
      els.sectionList.appendChild(li);
    });

    setStatus(`✓ Saved ${files.length} files as ${folder}.zip (~${formatCount(totalTokens)} tokens)`, "ok");
    // Revoke after the download has had time to start.
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  } catch (err) {
    setStatus("Error: " + (err && err.message ? err.message : String(err)), "err");
  } finally {
    els.btn.disabled = false;
  }
}

els.btn.addEventListener("click", run);

// --- Crawl whole section: gather sidebar links, hand off to the crawler tab ---
async function startCrawl() {
  els.crawlBtn.disabled = true;
  setStatus("Scanning sidebar for doc links…");
  try {
    const tab = await getActiveTab();
    if (!tab || !tab.id) throw new Error("No active tab found.");
    if (/^(chrome|edge|about|chrome-extension):/.test(tab.url || "")) {
      throw new Error("Open a real docs page first.");
    }

    const [injection] = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: collectSidebarLinks,
    });
    const result = injection && injection.result;
    if (!result || !result.ok) {
      throw new Error((result && result.error) || "Could not read links.");
    }
    if (!result.links.length) {
      throw new Error("No links found on this page.");
    }

    await chrome.storage.local.set({
      crawlJob: {
        origin: result.origin,
        baseSegment: result.baseSegment,
        pageTitle: result.pageTitle,
        current: result.current,
        fromNav: result.fromNav,
        folderHint: els.folderName.value || "",
        includeRaw: els.includeRaw.checked,
        includeCombined: els.includeCombined.checked,
        links: result.links,
        createdAt: Date.now(),
      },
    });

    await chrome.tabs.create({ url: chrome.runtime.getURL("crawler.html") });
    window.close(); // hand off to the crawler page
  } catch (err) {
    setStatus("Error: " + (err && err.message ? err.message : String(err)), "err");
    els.crawlBtn.disabled = false;
  }
}

els.crawlBtn.addEventListener("click", startCrawl);
