import { htmlToMarkdown } from "./html2md.js";
import { createZip } from "./zip.js";
import { extractPageSections } from "./extractor.js";

const els = {
  btn: document.getElementById("ingestBtn"),
  folderName: document.getElementById("folderName"),
  includeRaw: document.getElementById("includeRaw"),
  status: document.getElementById("status"),
  previewWrap: document.getElementById("previewWrap"),
  sectionList: document.getElementById("sectionList"),
  sectionCount: document.getElementById("sectionCount"),
};

function setStatus(msg, kind) {
  els.status.hidden = false;
  els.status.textContent = msg;
  els.status.className = "status" + (kind ? " " + kind : "");
}

function slugify(text, fallback) {
  const s = (text || "")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return s || fallback;
}

// First meaningful sentence/line of a markdown blob, for the index summary.
function summarize(markdown) {
  const lines = markdown.split("\n");
  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith("#") || t.startsWith("```") || t.startsWith("|")) continue;
    const clean = t.replace(/[*_`>#-]/g, "").trim();
    if (clean.length > 0) {
      return clean.length > 160 ? clean.slice(0, 157) + "…" : clean;
    }
  }
  return "(no description)";
}

async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}

async function run() {
  els.btn.disabled = true;
  setStatus("Reading page…");

  try {
    const tab = await getActiveTab();
    if (!tab || !tab.id) throw new Error("No active tab found.");
    if (/^(chrome|edge|about|chrome-extension):/.test(tab.url || "")) {
      throw new Error("Cannot ingest browser/internal pages. Open a real docs page.");
    }

    const [injection] = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: extractPageSections,
    });

    const result = injection && injection.result;
    if (!result || !result.ok) {
      throw new Error((result && result.error) || "Extraction failed.");
    }
    if (!result.sections.length) {
      throw new Error("No content sections detected on this page.");
    }

    setStatus(`Converting ${result.sections.length} sections to Markdown…`);

    const folder = slugify(els.folderName.value || result.title, "documentation");
    const now = new Date();
    const usedNames = new Set();
    const files = [];
    const indexEntries = [];

    result.sections.forEach((section, i) => {
      const markdown = htmlToMarkdown(section.html);
      const num = String(i + 1).padStart(2, "0");
      let base = `${num}-${slugify(section.title, "section")}`;
      let name = `${base}.md`;
      let dedupe = 2;
      while (usedNames.has(name)) name = `${base}-${dedupe++}.md`;
      usedNames.add(name);

      const heading = "#".repeat(Math.max(1, section.level || 1));
      const body = `${heading} ${section.title}\n\n${markdown}`;
      files.push({ name: `${folder}/${name}`, text: body });

      indexEntries.push({
        title: section.title,
        file: name,
        summary: summarize(markdown),
      });

      if (els.includeRaw.checked) {
        files.push({ name: `${folder}/raw/${base}.html`, text: section.html });
      }
    });

    // Build index.md
    let index = `# ${result.title}\n\n`;
    index += `> Ingested from [${result.url}](${result.url})\n`;
    index += `> on ${now.toISOString().slice(0, 10)} · ${indexEntries.length} sections\n\n`;
    index += `## Contents\n\n`;
    indexEntries.forEach((e, i) => {
      index += `${i + 1}. **[${e.title}](./${e.file})** — ${e.summary}\n`;
    });
    index += `\n---\n\n_Generated by the Documentation Ingester Chrome extension._\n`;
    files.unshift({ name: `${folder}/index.md`, text: index });

    setStatus("Building ZIP…");
    const blob = createZip(files, now);
    const url = URL.createObjectURL(blob);

    await chrome.downloads.download({
      url,
      filename: `${folder}.zip`,
      saveAs: false,
    });

    // Render preview.
    els.previewWrap.hidden = false;
    els.sectionCount.textContent = String(indexEntries.length);
    els.sectionList.innerHTML = "";
    indexEntries.forEach((e) => {
      const li = document.createElement("li");
      li.textContent = `${e.title} → ${e.file}`;
      els.sectionList.appendChild(li);
    });

    setStatus(`✓ Saved ${files.length} files as ${folder}.zip`, "ok");
    // Revoke after the download has had time to start.
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  } catch (err) {
    setStatus("Error: " + (err && err.message ? err.message : String(err)), "err");
  } finally {
    els.btn.disabled = false;
  }
}

els.btn.addEventListener("click", run);
